language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=pyasq setup.py test
after_success: coveralls
deploy:
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true
